# Generated by Django 3.2.9 on 2021-12-04 11:17

import clean.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='media', validators=[clean.validators.validate_file_extension])),
                ('is_wrangled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('selected', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='clean.file')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('null_choice_num', models.CharField(choices=[('nothing', 'Nothing'), ('remove-tuples', 'Remove tuples'), ('Avg', 'Average'), ('Med', 'Median'), ('Min', 'Minimum'), ('Max', 'Maximum'), ('Cus', 'Custom value')], default='remove-tuples', max_length=20, null=True)),
                ('null_choice_string', models.CharField(choices=[('nothing', 'Nothing'), ('remove-tuples', 'Remove tuples'), ('Cus', 'Custom string')], default='remove-tuples', max_length=20, null=True)),
                ('null_choice_date', models.CharField(choices=[('nothing', 'Nothing'), ('remove-tuples', 'Remove tuples'), ('Now', 'Current date'), ('Cus', 'Custom date')], default='remove-tuples', max_length=20, null=True)),
                ('current_type', models.CharField(choices=[('non', 'None'), ('Temperature', (('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin'))), ('Distance', (('KM', 'Kilometer'), ('MI', 'Mile'))), ('Weight', (('KG', 'Kilogram'), ('LB', 'Pound')))], default='NON', max_length=3, null=True)),
                ('desired_type', models.CharField(choices=[('non', 'None'), ('Temperature', (('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin'))), ('Distance', (('KM', 'Kilometer'), ('MI', 'Mile'))), ('Weight', (('KG', 'Kilogram'), ('LB', 'Pound')))], default='NON', max_length=3, null=True)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_preference', to='clean.header')),
            ],
        ),
    ]
