# Generated by Django 3.2.9 on 2021-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='remove_null_values',
            field=models.BooleanField(default=True),
        ),
    ]
