# Generated by Django 3.2.9 on 2021-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_cleaner_remove_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
