# Generated by Django 3.2.9 on 2021-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_alter_cleaner_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='remove_null_values',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='null_values',
            field=models.CharField(choices=[('DN', 'Do nothing'), ('RV', 'Remove values'), ('RA', 'Replace with avg.'), ('RM', 'Replace with median')], default='DN', max_length=2),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='remove_duplicate_rows',
            field=models.BooleanField(default=False),
        ),
    ]
