# Generated by Django 3.2.9 on 2021-11-24 07:40

import clean.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_auto_20211123_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='file',
            field=models.FileField(null=True, upload_to='media', validators=[clean.validators.validate_file_extension]),
        ),
    ]
