# Generated by Django 3.2.9 on 2021-11-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_auto_20211123_0839'),
        ('clean', '0004_auto_20211123_2002'),
    ]

    operations = [
    ]
