# Generated by Django 3.2.9 on 2021-11-24 08:40

import clean.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0005_alter_cleaner_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='media', validators=[clean.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columns', models.JSONField(default='["Temp", "Length", "PersonNumber", "Name", "PhoneNumber"]', verbose_name='Preferences')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='clean.file')),
            ],
        ),
        migrations.DeleteModel(
            name='Cleaner',
        ),
    ]
