# Generated by Django 3.2.9 on 2021-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0007_remove_preferences_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='columns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
