# Generated by Django 3.2.9 on 2021-11-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0008_file_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='columns',
        ),
        migrations.CreateModel(
            name='HeaderPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_preference', to='clean.header')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='clean.file'),
        ),
    ]
