# Generated by Django 3.2.9 on 2021-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0009_auto_20211125_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerpreference',
            name='data_type',
            field=models.CharField(choices=[('non', 'None'), ('Temperature', (('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin'))), ('Distance', (('KM', 'Kilometer'), ('MI', 'Mile'))), ('Weight', (('KG', 'Kilogram'), ('LB', 'Pound')))], default='non', max_length=3),
        ),
    ]
