# Generated by Django 3.2.9 on 2021-11-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0010_headerpreference_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerpreference',
            old_name='data_type',
            new_name='current_type',
        ),
        migrations.AddField(
            model_name='headerpreference',
            name='desired_type',
            field=models.CharField(choices=[('non', 'None'), ('Temperature', (('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin'))), ('Distance', (('KM', 'Kilometer'), ('MI', 'Mile'))), ('Weight', (('KG', 'Kilogram'), ('LB', 'Pound')))], default='non', max_length=3),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
