# Generated by Django 3.2.9 on 2021-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0012_auto_20211202_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headerpreference',
            name='current_type',
            field=models.CharField(choices=[('non', 'None'), ('Temperature', (('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin'))), ('Distance', (('KM', 'Kilometer'), ('MI', 'Mile'))), ('Weight', (('KG', 'Kilogram'), ('LB', 'Pound')))], default='NON', max_length=3),
        ),
    ]
