# Generated by Django 3.2.9 on 2021-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0014_auto_20211202_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerpreference',
            name='null_choice_date',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('remove-tuples', 'Remove tuples'), ('Now', 'Current date'), ('Cus', 'Custom date')], default='remove-tuples', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='headerpreference',
            name='null_choice_num',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('remove-tuples', 'Remove tuples'), ('Avg', 'Average'), ('Med', 'Median'), ('Min', 'Minimum'), ('Max', 'Maximum'), ('Cus', 'Custom value')], default='remove-tuples', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='headerpreference',
            name='null_choice_string',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('remove-tuples', 'Remove tuples'), ('Cus', 'Custom string')], default='remove-tuples', max_length=20, null=True),
        ),
    ]
